name: CI
on:
  push:
    branches: [ main ]
jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test
